name: apklis_payment_checker_example
description: Demonstrates how to use the apklis_payment_checker plugin.

publish_to: "none"

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  apklis_payment_checker:
    path: ../
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0

flutter:
  uses-material-design: true
